### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#103]
I've created a slack (galaxyadmintraining.slack.com) and created channels for the current planned topics.

![image](https://user-images.githubusercontent.com/458683/98926859-1f347700-24d8-11eb-8d2b-32e86bf7a81a.png)

The plan is students can chat within those channels to easily keep the topics separate, and our helpers will monitor those channels.

**Comment by afgane** [comment]
Perhaps a bit late given the channel has been setup but wanted to suggest the option of using Discord instead of Slack as an alternative without the 10,000 message history limit for free accounts. It be neat if we could move more of Galaxy in this direction so perhaps piloting it with the Admin training is an opportunity to lead the way?

**Comment by hexylena** [comment]
We have decided for this training, but maybe we could consider that next time.

The 10k messages was not a significant concern (given the presence of a planned FAQ document, usage rates during ML elixir webinar, other slacks I'm on, etc.)
