### ISSUE TITLE
Merge ToolShed slide deck into the ephemeris

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#106]
lot of duplication/overlapping. I can do/help with that --  @nsoranzo 
 
@cat-bro

**Comment by cat-bro** [comment]
I have some notes on the slides.  I'd be happy to update these.

**Toolshed notes:**

A slide with a diagram of public galaxy and private galaxy in cloud icons with arrows.  I skipped over this in July because I didn’t understand it.  We could either remove it or write presenter notes for it.
https://training.galaxyproject.org/training-material/topics/admin/tutorials/toolshed/slides.html#p6

There is an explanation of the .shed.yml file.  A simple .xml file would also be useful.  We could explain the concept of owner and the name+owner is the unique id
https://training.galaxyproject.org/training-material/topics/admin/tutorials/toolshed/slides.html#p9

In general more visuals for this would be good, perhaps a single slide showing a tool the galaxy tool panel and a single slide showing what the toolshed main page looks like.  

**Ephemeris notes:**

Instead of having a slide of the workflow-install command we could have one for workflow-to-tools.  It makes more sense to generate the .yml from the workflow before installing, some tools might belong in different sections (and also this is what we will do in the hands-on)
https://training.galaxyproject.org/training-material/topics/admin/tutorials/tool-management/slides.html#8

There is a slide on ‘get-tool-list’, then the following slide contains tool yaml which cannot have been generated from get-tool-list because it contains ‘install_resolver_dependencies’ key.  Update this
https://training.galaxyproject.org/training-material/topics/admin/tutorials/tool-management/slides.html#10

Change TS to toolshed in this header.  This and following slide could be moved back to before ephemeris is introduced
https://training.galaxyproject.org/training-material/topics/admin/tutorials/tool-management/slides.html#p17

Dependency resolvers slides explaining how to resolve dependency bar for tool foo could be all in one diagram.  This is also the part I would skip if running out of time.

**Comment by hexylena** [comment]
I definitely want good presenter notes for all of these :)

Toolshed

1. Drop this is important for maybe 5% of admins. We don't want to encourage private toolsheds right? Those with the complaint of "but my private tools" will ask and find that it's possible
2. sounds good.
3. Wow, not even one TS screenshot. Definitely! admins **need** to be able to navigate this

ephemeris

1. agreed.
2. +1
3. +1
4. Dependency resolvers feels more like a job conf topic a bit to me? Should we move it there?

**Comment by nsoranzo** [comment]
I've done the merge as promised in https://github.com/galaxyproject/training-material/pull/2178 , could be a good starting base for your other improvements @cat-bro ?

**Comment by hexylena** [comment]
This looks like such a fantastic start! Thanks so much @nsoranzo, looking forward to your other planned additions @cat-bro.

**Comment by hexylena** [comment]
xef https://github.com/galaxyproject/training-material/pull/2203
